### ISSUE TITLE
About NotchFilter

### ISSUE THREAD

**Issue by Vol561** [DASAR/Minim-Android#2]
I try to use music NotchFilter filter specific Hertz, but to filter is not complete.
   I want to filter out the part of the 3000-5000 hz,I save the filtered audio, using software to analyze the audio, found 3000-5000 hz has not been completely filtered out

This is the part of the code:
float[][] signals = deinterleaveData(shortToFloat(buffer), 2);
notchLeft.process(signals[0]);
notchRight.process(signals[1]);
float[] newBuffer = interleaveData(signals);
if (buffer.length < newBuffer.length)
    buffer = new short[newBuffer.length];
for (int i = 0; i < newBuffer.length; i++)
    buffer[i] = (short) (newBuffer[i] \* Short.MAX_VALUE);

I put the audio data is split into two channels, filtering respectively, then together.
 I'm not sure what's wrong.Do you know what could be a problem?

**Comment by Vol561** [comment]
supplement：
notchLeft = new NotchFilter(4000, 2000,44100);
notchRight = new NotchFilter(4000, 2000,44100);

![image](https://cloud.githubusercontent.com/assets/16773396/12413255/7614ad40-bec8-11e5-9317-9d49c3d83c52.png)

**Comment by DASAR-zz** [comment]
Try to use this method instead to process Stereo buffer:

``` java
process(float[] sigLeft, float[] sigRight) 
```

**Comment by Vol561** [comment]
Thank you for your answer.
but I need to use different filter in left and right（for example：left:1000-1500,right:3000-3500）
and now the question is: when I filter the audio data below 2000 hz, there will be a noise
